# Generated by Django 4.2.5 on 2023-11-29 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0009_alter_plant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.BigIntegerField(default=0)),
                ('garden_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden_section')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.plant')),
            ],
        ),
    ]
