# Generated by Django 4.2.5 on 2023-11-29 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0010_plant_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_log',
            name='garden_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gardens.garden_section'),
        ),
        migrations.AlterField(
            model_name='plant_log',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gardens.plant'),
        ),
    ]
