# Generated by Django 4.2.5 on 2023-12-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0011_alter_plant_log_garden_section_alter_plant_log_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='variety',
        ),
    ]
