# Generated by Django 4.2.5 on 2023-12-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0012_rename_name_plant_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='seed',
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gardens.plant_category'),
        ),
    ]
