# Generated by Django 4.2.5 on 2023-12-02 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0013_remove_plant_seed_alter_plant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('text', models.TextField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='gardens.plant')),
            ],
        ),
    ]
